name: 🚀 Deploy MERN Ecommerce Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build React App
        working-directory: ./MERN-Stack-Ecommerce-App-master
        run: |
          npm install
          CI=false npm run build

      - name: Create app folder on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: mkdir -p /home/ubuntu/app

      - name: Upload build folder
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "MERN-Stack-Ecommerce-App-master/build"
          target: "/home/ubuntu/app"
          overwrite: true

      - name: Upload Dockerfile
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "MERN-Stack-Ecommerce-App-master/Dockerfile"
          target: "/home/ubuntu/app"

      - name: Build + Run Docker container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/app
            docker rm -f frontend || true
            docker build -t fusion-frontend .
            docker run -d --name frontend -p 80:80 fusion-frontend
